themoment-team/GSM-Networking-server

build.gradle.kts, src/main/kotlin/team/themoment/gsmNetworking/common/exception/StompException.kt, src/main/kotlin/team/themoment/gsmNetworking/common/socket/message/StompMessage.kt, src/main/kotlin/team/themoment/gsmNetworking/common/socket/model/StompErrorResponse.kt, src/main/kotlin/team/themoment/gsmNetworking/common/socket/sender/StompSender.kt, src/main/kotlin/team/themoment/gsmNetworking/global/config/StompWebSocketConfig.kt, src/main/kotlin/team/themoment/gsmNetworking/global/exception/handler/GlobalSocketExceptionHandler.kt, src/main/kotlin/team/themoment/gsmNetworking/global/socket/handler/CustomStompSubProtocolErrorHandler.kt, src/main/kotlin/team/themoment/gsmNetworking/global/socket/processor/StompErrorProcessor.kt
WebSocket & STOMP 환경설정과 Socket Exception Handling 기능을 구현하였습니다.
- `StompWebSocketConfig` : STOMP를 사용하기위한 config 객체
- `StompMessage`
- STOMP 통신 시 사용할 Wrapper 객체
- Sender를 사용해 통신 시 DTO를 사용하게 됩니다, 타입 지정이 필요하면 시 Any 타입으로 지정해야 하는데, 안전성이나 유지보수 면에서 좋지 않다고 생각해 해당 클래스를 사용하도록 하였습니다.
- `CustomStompSubProtocolErrorHandler` : STOMP 통신 중, Interceptor 발생하는 exception을 처리하는 Handler
- `GlobalSocketExceptionHandler` : 전역으로 Socket 예외를 처리하는 Handler
- `StompErrorProcessor` : StompError를 사용자에게 전달하는 객체, StompErrorSender 에게 처리를 위임합니다.
- `StompSender` :  Stomp 메시지와 에러를 사용자에게 전달하는 역할의 인터페이스
- `StompException` : Client에게 예외 상황을 전달하기 위해 사용하는 Exception
=> WebSocket & STOMP 환경설정 및 Socket Exception Handling 기능 추가

src/main/resources/application-local.yml, src/main/resources/application-prod.yml
=> application-prod에 빠진 환경변수 추가

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/domain/TempMentor.kt
기존 Firebase에 저장되던 유저 정보를 저장하는 엔티티 객체 `TempMentor`를 구현하였습니다.
=> TempMentor 구현

src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
api 접근 권한 수정
멘티의 권한을 전환하는 api에 대한 접근 권한을 수정하였습니다.
=> 멘티 권한 전환 api에 대한 접근 권한 수정

src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
FilterConfig 생성자에 loggingFilter가 빠져있었는데 추가하였습니다.
=> FilterConfig 생성자에 loggingFilter추가

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/controller/TempMentorController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/CompanyInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/SearchTempMentorListDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/TempMentorListDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/TempMentorRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryTempMentorListService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/SearchTempMentorListService.kt
검색해서 TempMentor리스트를 반환하는 로직
이름을 받아서 검색해서 TempMentor리스트를 반환하는 로직을 구현하였습니다.
=> 이름을 받아서 TempMentor리스트를 반환하는 로직 구현

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/controller/TempMentorController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/domain/TempMentor.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/TempMentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/TempMentorRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/DeleteTempMentorService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryTempMentorListService.kt, src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
TempMentor를 삭제하는 기능을 구현하였습니다.
TempMentor를 논리적으로 삭제하는 기능을 구현하였습니다. 논리적으로 삭제된 TempMentor를 반환하는 등의 기능은 없어서 `@Where(clause = "deleted = false")`로 설정하였습니다.
=> TempMentor 삭제하는 기능 구현

src/main/resources/application-prod.yml
actuator 설정이 local yml에만 추가 되고 prod yml에 추가가 안되있어서 추가하였습니다.
=> prod actuator 설정 추가

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/controller/MentorController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/MentorRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/DeleteMeMentorService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/DeleteMyMentorInfoService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/user/repository/UserRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
자신의 멘토 정보를 삭제하는 기능
자신의 멘토 정보를 삭제하는 기능을 구현하였습니다.
실제 기능으로는 사용하지 않고 테스트 할때만 사용된다고 합니다.
=> 자신의 멘토 정보를 삭제하는 기능을 구현

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/controller/TempMentorController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/SearchTempMentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/CareerRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/TempMentorRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/DeleteMyMentorInfoService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/DeleteTempMentorService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryTempMentorService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/SearchTempMentorListService.kt
특정 임시멘토를 가져오는 로직 구현
특정 임시멘토를 가져오는 로직을 구현하였습니다.
지금까지 작성한 코드에 대한 자바독을 작성하지 않았던것 같아서 자바독을 작성하였습니다.
=> 특정 임시멘토를 가져오는 로직 구현

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/controller/TempMentorController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/TempMentorRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryAllMentorsListService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/SearchTempMentorListService.kt
search api에서 정확한 이름으로 찾아서 반환하는 query api로 변경하였습니다.
=> 임시멘토 search 에서 찾아서 반환하는 query로 변경

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/MentorCareerDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/MentorRegistrationService.kt
dto에서 companyUrl을 nullable하게 변경하였습니다
=> MentorCareerDto의 companyUrl을 nullable로 변경

src/main/kotlin/team/themoment/gsmNetworking/global/exception/handler/GlobalExceptionHandler.kt
=> 예외처리 되지 않은 예외를 처리

src/main/kotlin/team/themoment/gsmNetworking/common/util/DateValueUtil.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/domain/Career.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/MentorCareerDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/MentorRegistrationService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/util/DateValueUtil.kt
Career의 endDate를 nullable로 변경
Career의 endDate를 nullable로 변경하고 db에 null 대신 들어갈 임의의 값을 넣었습니다.
=> Career의 endDate를 nullable로 변경

src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
=> :ambulance: api 접근 권한 수정

src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
=> api 접근 권한 수정

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/MyCareerInfoDto.kt
MyCareerInfoDto에서 필드를 nullable로 변경하였습니다.
MyCareerInfoDto에서 원래 nullable이여야할 필드에 nullable을 깜빡했어서 변경하였습니다.
=> MyCareerInfoDto에서 필드를 nullable로 변경

src/main/kotlin/team/themoment/gsmNetworking/global/filter/LoggingFilter.kt
Http Request에 body가 출력되지 않는 문제를 해결하였습니다.
자세한 설명은 #77 를 참고해주세요.
=> Http Request에 body가 출력되지 않는 문제 해결

src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/repository/GwangyaCustomRepositoryImpl.kt
광야 게시물을 가지고 와서 나온 반환값을 reverse해서 반환하였습니다.
desc로 최신글을 먼저 나오게 하고 그 최신글에 대한 반환값을 reversed해서 반환하도록 하였습니다.
=> 광야 리스트 결과값을 reverse해서 반환하도록 수정

src/main/kotlin/team/themoment/gsmNetworking/global/exception/handler/GlobalExceptionHandler.kt
MethodArgumentNotValidException을 핸들링하는 핸들러를 구현하였습니다.
=> MethodArgumentNotValidException 핸들러 구현

src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/controller/GwangyaController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/service/DeleteGwangyaByIdService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/service/DeleteGwangyaService.kt, src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
광야 게시물 삭제 로직을 구현하였습니다.
욕설과 부적절한 광야 게시물이 생겼을시 ADMIN계정으로 삭제할 수 있도록 추가하였습니다.
=> 광야 게시물 삭제 로직 구현

src/main/kotlin/team/themoment/gsmNetworking/global/exception/handler/GlobalExceptionHandler.kt
500 http status 발생 후 메세지 반환시 사용자 친화적으로 변경하였습니다.
=> 500 발생시 메세지를 사용자 친화적으로 변경

src/main/kotlin/team/themoment/gsmNetworking/common/socket/message/GlobalMessageCode.kt, src/main/kotlin/team/themoment/gsmNetworking/common/socket/message/MessageCode.kt, src/main/kotlin/team/themoment/gsmNetworking/common/socket/message/StompMessage.kt, src/main/kotlin/team/themoment/gsmNetworking/common/util/UUIDUtils.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/code/MessageMessageCode.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/HeaderRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/MessageCustomRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/MessageRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/UserMessageInfoRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/CheckMessageService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/QueryMessageService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/SaveMessageService.kt
채팅 관련 객체에 KDoc 작성/보완 하였습니다.
약간의 코드 레이아웃 변경이 존재합니다. 
기능적인 수정은 없으므로 크게 중요하지 않게 보셔도 될 것 같습니다.
=> 채팅 관련 객체 KDoc 작성

src/main/kotlin/team/themoment/gsmNetworking/common/socket/message/GlobalMessageCode.kt, src/main/kotlin/team/themoment/gsmNetworking/common/socket/message/MessageCode.kt, src/main/kotlin/team/themoment/gsmNetworking/common/socket/message/StompMessage.kt, src/main/kotlin/team/themoment/gsmNetworking/common/socket/sender/StompSender.kt, src/main/kotlin/team/themoment/gsmNetworking/common/util/UUIDUtils.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/domain/Header.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/domain/UserMessageInfo.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/code/MessageMessageCode.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/domain/MessageMetaDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/HeaderRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/MessageCustomRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/MessageCustomRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/MessageRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/UserMessageInfoRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/CheckMessageService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/QueryMessageService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/SaveMessageService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/impl/CheckMessageServiceImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/impl/QueryMessageServiceImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/impl/SaveMessageServiceImpl.kt
개발된 신규 기능 중 일부가 main 브랜치로 올라가는 문제가 발생했습니다.
main에 반영된 기능을 develop으로 이동시키려고 합니다.
해당 PR이 완료되면 main 브랜치는 release 이전 시점으로 rollback하겠습니다.
=> 신규 기능을 develop 브랜치로 이동

src/main/kotlin/team/themoment/gsmNetworking/global/exception/handler/GlobalExceptionHandler.kt
MethodArgumentTypeMismatchException의 핸들러를 구현하였습니다.
=> MethodArgumentTypeMismatchException 핸들러 구현

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/MyMentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/MentorCustomRepositoryImpl.kt
내 멘토 정보를 가져올때 phoneNumber도 가져오도록 추가하였습니다.
=> 내 맨토 정보 가져오기에 phoneNumber 필드 추가

scripts/deploy.sh
timezone을 한국시간으로 설정
jar 파일을 실행할때 timezone을 한국시간으로 설정하도록 `-Duser.timezone=Asia/Seoul`을 추가하였습니다.
=> jar 파일 실행 시 timezone을 한국시간으로 설정

src/main/kotlin/team/themoment/gsmNetworking/domain/board/domain/BoardCategory.kt, src/main/kotlin/team/themoment/gsmNetworking/global/exception/handler/GlobalExceptionHandler.kt, src/main/resources/application-local.yml
게시글 카테고리 누락된 필드 추가, 예외 핸들러 메서드 추가
- 게시글의 카테고리 중 `SHARE` 카테고리 필드가 누락되어 추가하였습니다.
- `HttpMessageNotReadableException` 요청 바디의 값이 유효하지 않을 때 발생하는 예외를 핸들링하는 메서드를 추가하였습니다.
=> 게시글 카테고리 누락 필드 추가 및 관련 예외 핸들링

src/main/kotlin/team/themoment/gsmNetworking/domain/comment/dto/AuthorDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/domain/TempMentor.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/MentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/SearchTempMentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/TempMentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/user/domain/User.kt
defaultImgNumber 필드를 nullable 하게 변경하였습니다.
=> defaultImgNumber 필드 nullable

src/main/kotlin/team/themoment/gsmNetworking/domain/board/domain/BoardCategory.kt
=> 취업 카테고리 추가

src/main/kotlin/team/themoment/gsmNetworking/domain/user/service/GenerateUserUseCase.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/user/service/impl/UserService.kt
멘티에서 멘토로 전환할때 발생하는 문제를 해결하였습니다.
멘티에서 멘토로 전환할때 멘토 등록 api를 사용하게 되는데 서버에서는 멘토 등록 api에서 별다른 처리를 하고있지 않고 있었습니다.
이번 릴리즈때 반영되면 좋다고해서 급하게 해결해놓았습니다.
추후에 코드 리펙토링이 필요해 보여요
=> 멘티에서 멘토로 전환할때 발생하는 문제 해결

src/main/kotlin/team/themoment/gsmNetworking/domain/user/domain/User.kt
comment에 추가된 author_id관련해서 내 멘토정보삭제시 제약조건 위반 에러가 발생했습니다.
- commet와 user엔티티간의 caseCade를 ALL로 설정하여 오류를 해결하였습니다.
=> 댓글, 유저 cascade ALL 추가

src/main/kotlin/team/themoment/gsmNetworking/global/socket/interceptor/StompInterceptor.kt
Stomp preSend 메서드의 if-else state를 when-is로 변경하였습니다.
=> Stomp preSend 메서드 리팩토링

src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
광야 토큰 발급시 TEACHER Authority인 사용자도 허용하도록 추가하였습니다.
\+ 선생님 권한도 유저와 동등한 권한을 가지도록 추가로 변경하였습니다.
=> 광야 토큰 발급시 Authority 추가

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/GenerateCompanyAddressUseCase.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/impl/MentorService.kt, src/test/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryAllMentorsUseCaseTest.kt
https://github.com/themoment-team/GSM-Networking-server/pull/162
위 pr 작업내용때문에 실패하는 test 코드를 수정하였습니다.
=> 실패하는 테스트코드 수정

src/main/kotlin/team/themoment/gsmNetworking/domain/board/repository/BoardCustomRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/impl/BoardService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/comment/dto/AuthorDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/comment/service/impl/CommentService.kt
게시글, 댓글 조회 dto 객체에 작성자의 id 필드를 추가하였습니다.
=> 게시글, 댓글 작성자 id 필드 추가

src/main/kotlin/team/themoment/gsmNetworking/domain/board/controller/BoardController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/dto/BoardListDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/repository/BoardCustomRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/SaveBoardUseCase.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/impl/BoardService.kt
게시글 리스트 조회시 이미지 파일 필드가 추가되어있어서 해당 부분을 제거하였습니다.
=> 게시글 리스트 파일 필드 제거

src/main/kotlin/team/themoment/gsmNetworking/domain/board/controller/BoardController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/dto/BoardSaveDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/dto/BoardUpdateDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/SaveBoardUseCase.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/UpdateBoardUseCase.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/impl/BoardService.kt, src/main/kotlin/team/themoment/gsmNetworking/thirdParty/aws/s3/service/FileUploadUseCase.kt, src/main/kotlin/team/themoment/gsmNetworking/thirdParty/aws/s3/service/impl/S3Service.kt
- multiPartFile을 dto가 아닌 requestPart로 변경
=> 게시물 파일 업로드 기능 재 구축

src/main/kotlin/team/themoment/gsmNetworking/domain/board/controller/BoardController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/UpdateBoardUseCase.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/impl/BoardService.kt
- 파일 업로드 시 잘못되어있던 조건문을 수정하였습니다.
=> 게시물 파일 업로드 조건문 수정

src/main/kotlin/team/themoment/gsmNetworking/domain/board/domain/Board.kt
=> 게시글, 파일 관련 엔티티 수정

src/main/kotlin/team/themoment/gsmNetworking/domain/board/controller/BoardController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/domain/File.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/dto/FileInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/SaveBoardUseCase.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/UpdateBoardUseCase.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/impl/BoardService.kt, src/main/kotlin/team/themoment/gsmNetworking/thirdParty/aws/s3/service/FileUploadUseCase.kt, src/main/kotlin/team/themoment/gsmNetworking/thirdParty/aws/s3/service/impl/S3Service.kt
- 파일 이름 필드를 추가하였습니다.
- 파일없이 요청을 보내면 문제가 발생하던 부분을 해결하였습니다.
=> 파일 이름 필드 추가
