themoment-team/GSM-Networking-server

src/main/kotlin/team/themoment/gsmNetworking/common/manager/AuthenticatedUserManager.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/auth/domain/Authentication.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentee/controller/MenteeController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentee/service/UpdateMenteeService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/controller/MentorController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/user/domain/User.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/user/repository/UserRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/user/service/UserRegistrationService.kt
- 멘티, 멘토의 권한을 수정하는 기능을 추가하였습니다. 
- `authentication` 엔티티의 중복되면 안되는 컬럼에 `unique` 옵션을 추가하였습니다. 
- `user` 엔티티에 `authenticationId` 필드를 추가하였습니다. 
- 멘티의 경우 따로 데이터를 저장하는 구조가 아니라서, 권한만 `UNAUTHENTICATED`에서 `TEMP_USER`로 수정하도록 구현하였습니다.
- `mentorController`의 멘토 생성 메서드 이름을 `saveMentorInfo`에서 `mentorRegistration`으로 변경하였습니다.
=> 멘티, 멘토 권한 수정 기능 추가

build.gradle.kts, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/controller/MentorController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/MentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/CustomMentorRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryMentorListService.kt, src/main/kotlin/team/themoment/gsmNetworking/global/config/QueryDslConfig.kt
- 멘토 리스트를 가져오는 기능을 추가하였습니다.
- user, career, mentor 총 3개의 entity 값이 필요한 쿼리라 queryDsl을 추가하여 한 쿼리로 값을 리턴하도록 구현하였습니다.
=> 멘토 리스트 가져오는 기능 추가

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/MentorCustomRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/MentorCustomRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/MentorRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryMentorListService.kt
디스코드에서 말한대로 같은 기능을 하는 `Repository`를 두개 따로 두는것보단, 공통된것을 같이 두는게 나아 인터페이스를 만들고 `MentorRepository`에서 다중 상속을 하도록 구현하였습니다.
`MentorCustomRepository`, `MentorCustomRepositoryImpl` 을 추가하였습니다.
=> 커스텀 Repository 인터페이스 추가

build.gradle.kts, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/domain/BaseChat.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/domain/BaseContent.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/domain/ChatType.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/domain/SystemChat.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/domain/TextContent.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/domain/UserChat.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/domain/ChatRoom.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/domain/ChatUserInfo.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/domain/Room.kt, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
채팅 서비스를 위한 `Chat`,`Room` 도메인을 구현하였습니다.
Chat,Room 도메인은 MongoDB에 저장됩니다.
MongoDB 의존성을 추가하고 관련 환경변수 설정을 적용하였습니다.
로컬 MongoDB 환경 구축 시에는 아래 링크를 참고해주세요.
https://poiemaweb.com/docker-mongodb
상속 방식이 복잡하기도 하고, 잘 다루기 어려워서 권장하는 구조는 아니라고 알고 있습니다.
https://www.inflearn.com/questions/30642/%EC%83%81%EC%86%8D%EA%B4%80%EA%B3%84-entity%EA%B0%84-%EC%A1%B0%EC%9D%B8
그럼에도 상속을 사용한 이유로는 다음과 같습니다.
- MongoDB를 사용하여 RDBMS와 달리 데이터 구조가 제한적이지 않습니다.
- 확장성이 더 좋습니다. 특히 앞으로 어떤 종류의 채팅이 추가되거나, 어떤 기능을 추가할 지 명확하지 않은 상황인만큼 확장성이 더 중요하다고 생각했습니다.
=> MongoDB 의존성 추가 & Chat,Room 도메인 구현

src/main/kotlin/team/themoment/gsmNetworking/GsmNetworkingApplication.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/domain/BaseChat.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/domain/SystemChat.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/domain/UserChat.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/enums/ChatType.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/repository/ChatQueryRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/repository/ChatQueryRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/repository/ChatRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/domain/ConnectedRoomUser.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/domain/Room.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/domain/RoomUser.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/repository/ConnectedRoomUserRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/repository/RoomQueryRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/repository/RoomQueryRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/repository/RoomRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/repository/RoomUserRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/global/config/EnableJpaAuditingConfig.kt
Room과 Chat 도메인의 엔티티와 레포지토리를 구현하였습니다.
Chat 도메인의 엔티티는 상속을 사용하여 확장성을 고려하였습니다.
추상 클래스 `BaseChat`을 구현한 `UserChat`, `SystemChat`이 존재합니다.
`Room`은 채팅방 정보를 포함합니다.
User와 Room은 N:M 관계를 가지기 때문에 조인 엔티티`RoomUser`가 추가되었습니다.
`RoomUser`는 사용자와 채팅방 사이의 관계를 연결해주며, 채팅방 이름, 마지막으로 본 시간 등 추가적인 정보를 포함합니다.
또한 사용자와 다른 도메인이기 때문에 객체 참조를 사용하지 않았습니다.
참고 : [우아한 테크 세미나] 우아한 객체지향 1:04:00 ~ 1:18:00
https://www.youtube.com/watch?v=dJ5C4qRqAgA&t=4537s
또한, `RoomUser`는 `Room` 과 밀접한 관계가 있고, 따로 사용되는 일이 적을 것 같아 `RoomUserRepository`은 QueryDSL을 사용하지 않고 `CrudRepository`의 기능만 사용하려고 합니다.
`ConnectedRoomUser`는 현재 채팅방에 접속한 사용자를 확인하며, 접속 여부에 따라 Socket 응답 or 알림(아직 구현계획 없음)이 실행됩니다.
=> Room & Chat 엔티티, 레포지토리 구현

build.gradle.kts, src/main/kotlin/team/themoment/gsmNetworking/common/util/UUIDUtils.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/domain/BaseChat.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/domain/SystemChat.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/domain/UserChat.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/dto/domain/BaseChatDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/dto/domain/RecentChatQueryDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/enums/Direction.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/repository/ChatQueryRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/repository/ChatQueryRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/domain/ConnectedRoomUser.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/domain/Room.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/domain/RoomUser.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/dto/domain/RoomUserDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/repository/RoomQueryRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/repository/RoomQueryRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/global/config/EnableJpaAuditingConfig.kt, src/main/kotlin/team/themoment/gsmNetworking/global/socket/processor/StompErrorProcessor.kt
Chat/Room 도메인 엔티티를 수정하고, Repository 메서드를 구현하였습니다.
1. 인덱스 설정 추가
2. 테이블 이름을 `@Entity` 대신 `@Table` 에서 정의하도록 변경
3. 일부 잘못된 `@Column` 설정 변경
4. Chat 엔티티 ID가 UUIDv7을 사용함
- 왜 UUID를 사용하는지는 [WIKI](https://github.com/themoment-team/GSM-Networking-server/wiki/%F0%9F%94%97-DB-%EC%8B%9D%EB%B3%84%EC%9E%90-%EA%B0%92%EC%9C%BC%EB%A1%9C-UUID-v7-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)에 정리해놓았음
chat 서비스에 사용되는 Query 메서드를 구현하였습니다.
앞으로 더 추가될 수도 있지만, 주로 사용할 복잡한 쿼리는 이 PR에 구현되어있습니다.
`RoomQueryRepositoryImpl#findCountUserRooms` 가 무조건 long 타입 숫자 하나만 반환하는데,(2이상, 0은 불가능) 
그럼 `fetchFirst` 대신 `fetchOne`을 사용하는게 좋을까요?
(해당 내용 관련된 주석이 실수로 지워지지 않았는데, 수정하도록 하겠습니다.)
그리고 `fetchOne`을 사용하는 경우 반환 타입이 `Long?` 인데, 어느 단에서 예외처리를 하는게 적절할까요.
사용하는 쿼리 특성 상 `RoomQueryRepositoryImpl#findCountUserRooms` 내부에서 `!!` 을 사용할지, 외부에서 `?:` 을 사용할지 고민입니다.
=> Chat/Room 도메인 엔티티 수정 및 Repository 메서드 구현 

src/main/kotlin/team/themoment/gsmNetworking/global/filter/config/FilterConfig.kt
유효하지 않은 토큰일시 터지는 `ExpiredJwtException`, `JwtException`을 `ExceptionHandlerFilter` 로 못거르는 이슈를 해결하였습니다.
=> 유효하지 않은 accessToken 예외처리 추가

src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
cors config 추가
cors를 해결하기 위해 corsConfigurationSource를 생성하였습니다.
=> corsConfig를 구성하였습니다.

src/main/kotlin/team/themoment/gsmNetworking/global/filter/LoggingFilter.kt
LoggingFilter에서 Cookie가 Null인 request 로깅 시 NPE 발생하는 문제를 해결하였습니다.
nullable한 객체 `request.cookies`를 non-nullable하게 가져와서 NPE가 발생합니다.
`request.cookies?`로 nullable하게 변경하고, 
null이 아닌 경우에만 `joinToString`이 실행되도록 `.let` 을 추가하였습니다.
=> LoggingFilter에서 Cookie가 Null인 request 로깅 시 NPE 발생하는 문제 해결

src/main/kotlin/team/themoment/gsmNetworking/common/socket/sender/StompSender.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/controller/ChatMessageController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/dto/ws/request/QueryChatRequest.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/dto/ws/request/QueryRecentChatRequest.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/sender/ChatStompSender.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/service/QueryChatService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/chat/service/impl/QueryChatServiceImpl.kt
stomp 채팅 목록 가져오는 api를 구현하였습니다.
- `ChatStompSender`: 요청을 보낸 session에만 응답을 전송하는 `sendMessageToSession`를 구현하였습니다.
- 테스트 툴의 문제로 인해 valid 문이 대체되었습니다. 자세한 설명은 아래를 확인해주세요.
- `QueryRecentChatRequest`, `QueryChatRequest` : requset에 사용되는 dto입니다.
- `QueryChatService`, `QueryChatServiceImpl` : chat 목록을 가져오는 객체입니다.
- `ChatMessageController`: chat 요청 api를 받고 응답하는 메서드 `queryRecentChat`, `queryChat`을 추가하였습니다.
stomp 테스트에 apic 이라는 툴을 사용하는데, 툴에서 Connect와 Subscribe이 한 번에 처리됩니다.
실제로는 한 Connect에 여러 Subscribe이 가능해야 하는데, Apic에선 한 Connect이 한 Subscribe밖에 가질 수 없습니다.
이로 인해서 실제 환경과 동일한 상황에서 요청을 보낼 수 없는 문제가 있습니다.
더 좋은 툴을 찾고 자유롭게 테스트가 가능하면 `sendMessageToSession` valid 로직을 개선할 생각입니다.
=> stomp 채팅 목록 가져오는 api 추가

src/main/kotlin/team/themoment/gsmNetworking/global/config/StompWebSocketConfig.kt
alb -> ec2 환경에서 STOMP 통신을 사용하기 위해서 SockJs를 사용하도록 설정을 추가하였습니다.
SockJs를 사용하는 것 말고 다른 방법이 있지만, 가장 간편한 방법이라 사용하였습니다.
https://mumomu.tistory.com/134
=> STOMP SockJS 호환 설정 적용

src/main/kotlin/team/themoment/gsmNetworking/domain/room/controller/RoomMessageController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/dto/ws/RoomUserResponse.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/dto/ws/request/QueryRecentRoomsRequest.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/dto/ws/request/QueryRoomsRequest.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/mapper/RoomMapper.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/service/QueryRoomService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/service/QueryRoomServiceImpl.kt
방 목록을 요청하는 STOMP API를 구현하였습니다.
- `ChatMessageController#queryRecentRooms`: 최근 방 목록을 가져옵니다.
- `QueryRecentRoomsRequest` 해당 API의 RequestDto
- `ChatMessageController#queryRooms`: 요청한 시간대 이전의 방 목록을 가져옵니다.
- `QueryRoomsRequest` 해당 API의 RequestDto
최근 방 목록 또는 특정 시간 이전 방 목록을 불러오는 서비스 객체입니다.
`roomUserDtoToRoomUserResponse`, `roomUserDtoToRoomUserResponses` 메서드를 추가하였습니다.
`RoomUserResponse`에 `createAt` 필드를 추가하였습니다.
=> STOMP 방 목록 API 구현

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/domain/Career.kt
회사 사이트가 없는 회사를 대응하기 위한 `companyUrl` 컬럼을 nullable 로 수정하였습니다.
=> CompanyUrl 컬럼 nullable 로 수정

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/domain/Career.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/CareerRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/MentorRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/DeleteMyMentorInfoService.kt
멘토 삭제시 외래 키 제약조건에 의해 발생하는 에러를 해결하였습니다.
mentor삭제시 동작하지 않는 career의 mentor에 대한 cascade 코드를 삭제하였습니다.
추후 코드 변경이 필요할 수 있습니다.
=> 멘토 삭제 외래 키 제약조건 에러 해결

src/main/kotlin/team/themoment/gsmNetworking/domain/room/controller/RoomController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/dto/api/RoomRegistrationDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/dto/domain/FetchRoomDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/repository/RoomQueryRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/repository/RoomQueryRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/service/CreateRoomService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/service/CreateRoomServiceImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/service/QueryRoomService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/room/service/QueryRoomServiceImpl.kt
방 관련 HTTP API를 구현하였습니다.
`CreateRoomService#execute`
`QueryRoomService#findRoomByUserIds` 
- `#createRoom` :  방을 생성하고, 방 생성 시 생성된 SYSTEM CHAT 정보를 사용자에게 전달합니다.
- `#findRoomById` :  두 사용자의 ID를 받아서 두 사용자 사이의 채팅 방을 반환합니다.
=> 방 관련 HTTP API 구현

src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
session을 stateless로 설정하였습니다.
accessToken이 없는 상태로 멘토 리스트 등의 자원에 요청했을시 제대로 반환을 하는 등의 인증인가 부분의 문제가 있었습니다.
Jsession이 인증 인가를 대신 하는 문제가 있어서 session을 stateless로 설정하였습니다.
=> session을 stateless로 설정

build.gradle.kts, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/controller/MentorController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryAllMentorsService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/impl/QueryAllMentorsServiceImpl.kt, src/test/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryAllMentorsServiceTest.kt
=> 모든 맨토 조회 시 id가 non-unique 한 문제 해결 & 정렬된 상태로 반환하도록 변경

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/impl/QueryAllMentorsServiceImpl.kt, src/test/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryAllMentorsServiceTest.kt
모든 멘토 리스트에서 id를 재할당하지 않은 객체를 반환하고있어서 수정하였습니다.
=> 모든 멘토 리스트에서 잘못된 값을 반환하는 코드 수정

src/main/kotlin/team/themoment/gsmNetworking/common/util/StompPathUtil.kt, src/main/kotlin/team/themoment/gsmNetworking/common/util/UUIDUtils.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/domain/Header.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/domain/Message.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/domain/UserMessageInfo.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/domain/MessageDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/domain/MessageMetaDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/enums/QueryDirection.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/HeaderRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/MessageCustomRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/MessageCustomRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/MessageRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/UserMessageInfoRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/global/socket/sender/StompSenderImpl.kt
채팅 기능에 사용되는 domain, repository, 그 외 기타 객체를 구현하였습니다.
그 외 STOMP 관련 기능이 추가되었습니다.
이름과 주소가 변경되었습니다.
도메인에서 직접 서드파티 라이브러리를 호출해야 하는 문제가 있었습니다.
Util을 사용하여 호출하여 직접적인 의존성 없이 v7 UUID를 사용할 수 있게 변경하였습니다.
관련된 DTO, Enum 객체도 추가되었습니다.
**domain 객체 설명:**
- `Message` : 메시지
- `Header` : 사용자 사이의 채팅 관련 메타 정보 저장
- `UserMessageInfo` : 사용자 별 채팅 관련 정보
repository는 추후에 구현이 변경될 수 있으므로 내부 메서드에 대한 리뷰는 생략하셔도 됩니다.
구현이 완료되면 KDoc 추가하도록 하겠습니다.
=> 채팅 기능 domain&repository 객체 구현

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/controller/TempMentorController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/SearchTempMentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/TempMentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/TempMentorRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/DeleteTempMentorService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryTempMentorListService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryTempMentorService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/SearchTempMentorListService.kt, src/test/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryAllMentorsServiceTest.kt
firebaseId로 식별하던 api를 realId로 식별
firebase의존성을 제거한 이상 firebaseId가 필요가 없다고 하셔서 search/{name} api에서 받은 realId로 요청을 할거라고 하셨습니다.
임시멘토 테이블 컬럼에서 firebaseId를 제거하고 임시멘토 더미데이터 다시 삽입하는거에 대해서 어떻게 생각하시나요?
=> 임시멘토를 firebaseId 대신 realId로 식별

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/controller/TempMentorController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/SearchTempMentorListService.kt
이름 검색 api에서 빈 배열을 반환할 경우 예외처리를 하였습니다.
=> 이름 검색 api 빈 배열일 경우 예외처리

src/main/kotlin/team/themoment/gsmNetworking/common/socket/message/GlobalMessageCode.kt, src/main/kotlin/team/themoment/gsmNetworking/common/socket/message/MessageCode.kt, src/main/kotlin/team/themoment/gsmNetworking/common/socket/message/StompMessage.kt, src/main/kotlin/team/themoment/gsmNetworking/common/socket/sender/StompSender.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/controller/MessageHttpController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/controller/MessageWebsocketController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/domain/UserMessageInfo.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/code/MessageMessageCode.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/req/CheckMessageReq.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/req/QueryHeaderReq.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/req/QueryHeadersReq.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/req/QueryMessagesReq.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/req/SaveMessageReq.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/res/CheckMessageRes.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/res/HeaderRes.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/res/HeadersRes.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/res/MessageOccurRes.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/res/MessageRes.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/res/MessagesRes.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/res/SaveMessageRes.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/domain/HeaderDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/MessageRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/UserMessageInfoRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/CheckMessageService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/QueryMessageService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/SaveMessageService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/impl/CheckMessageServiceImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/impl/QueryMessageServiceImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/impl/SaveMessageServiceImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/global/exception/handler/GlobalSocketExceptionHandler.kt
채팅 API 및 비즈니스 로직을 구현하였습니다.
그 외 오류 수정과 Repository 메서드 추가 작업을 진행하였습니다.
- `SaveMessageService` : 채팅을 저장하고 채팅 관련 사용자 정보를 갱신합니다.
- `CheckMessageService` : 사용자가 특정 채팅을 확인한 상태로 변경합니다.
- `QueryMessageService` : 채팅과 관련된 객체를 가져옵니다.
- `MessageHttpController` : HTTP 요청을 매핑하는 Controller 입니다.
- `MessageWebsocketController` : Websocket(STOMP) 요청을 매핑하는 Controller 입니다.
UUID로 알맞게 변경하였습니다.
비즈니스 로직 구현에 필요하여 추가하였습니다.
=> 채팅 API 및 비즈니스 로직 구현

src/main/kotlin/team/themoment/gsmNetworking/domain/user/controller/UserController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/user/service/ProfileUrlRegistrationService.kt, src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
User 엔티티의 profileUrl을 등록 하는 로직을 구현하였습니다.
원래 mentor 등록할때 profileUrl도 같이 등록을 해야하는데 FE 사정으로 인해서 추가로 profileUrl 단독으로 등록하는 api를 요청하셔서 구현하였습니다.
=> User 엔티티의 profileUrl 등록 로직 구현

src/main/kotlin/team/themoment/gsmNetworking/domain/user/controller/UserController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/user/dto/ProfileUrlRegistrationDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/user/service/ProfileUrlRegistrationService.kt
profileUrl을 pathVariable에서 RequestBody로 받도록 수정하였습니다.
profileUrl을 pathVariable로 받을경우 url에 포함된 / 때문에 다른 api로 판단하게 되서 RequestBody로 받도록 수정하였습니다.
=> profileUrl을 pathVariable에서 RequestBody로 받도록 수정

src/main/kotlin/team/themoment/gsmNetworking/global/config/PropertiesScanConfig.kt, src/main/kotlin/team/themoment/gsmNetworking/thirdParty/aws/s3/properties/S3Properties.kt, src/main/kotlin/team/themoment/gsmNetworking/thirdParty/aws/s3/service/ImageUploadService.kt, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
이미지를 반환할때 s3 bucket 도메인을 변경 하였습니다.
기존 이미지 url의 도메인과 s3 image key 값을 분리 시키고 정해둔 imageBucketDomain 뒤에 s3 이미지 키 값을 위치시키고 반환하도록 하였습니다.
=> 이미지를 반환시 s3 bucket 도메인 변경 로직 구현

src/main/kotlin/team/themoment/gsmNetworking/common/socket/message/GlobalMessageCode.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/controller/MessageWebsocketController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/domain/UserMessageInfo.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/req/CheckMessageReq.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/api/res/CheckMessageRes.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/MessageCustomRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/CheckMessageService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/impl/CheckMessageServiceImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/impl/QueryMessageServiceImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/impl/SaveMessageServiceImpl.kt
채팅 check API 개선 작업을 수행했습니다.
`supportClass`가 `StompMessage`에서 `StompErrorResponse`로 올바르게 변경되었습니다.
- messageId를 참조할 때 서비스 결합도가 높아지는 문제가 있었습니다.
- 확인한 messageId가 삭제된 경우, 근처의 메시지를 확인하여 재할당해주는 로직이 필요했습니다.
- Message와 `UserMessageInfo` 간의 결합도가 높아졌습니다 (messageId의 유효성 확인 필요).
- messageId를 참조할 정도로 정확한 처리가 필요하지 않았습니다 (차이가 나더라도 millisec 단위).
- `UserMessageInfo` 엔티티 필드를 messageId(UUID)에서 unix time(Long)으로 수정했습니다.
- 필드 변경 사항에 맞게 서비스 객체, DTO, Controller도 수정했습니다.
=> 채팅 check API 개선

src/main/kotlin/team/themoment/gsmNetworking/global/exception/handler/GlobalExceptionHandler.kt, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
파일을 받을때 최대 용량이 디폴트(1MB)로 설정이 되어있어서 최대 파일 용량 설정을 추가하였습니다.
`MaxUploadSizeExceededException`을 핸들링 할때 저희가 `MaxUploadSizeExceededException`을 생성하는게 아니라서 예외 클래스 안에 있는 maxUploadSize를 가져왔을 경우 maxUploadSize에 값이 없어서 -1로 반환이 됩니다.
때문에  ResponseEntity body 메세지에 "파일 크기는 5MB를 넘을 수 없습니다." 라고 메세지를 보내도록 구현을 해놓았습니다.
피드백 부탁드립니다.
=> multipart 최대 파일 용량 설정 추가

src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/controller/GwangyaController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/domain/Gwangya.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/domain/GwangyaToken.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/dto/GwangyaPostsDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/dto/GwangyaPostsRegistrationDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/repository/GwangyaCustomRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/repository/GwangyaCustomRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/repository/GwangyaRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/service/GenerateGwangyaPostsService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/service/QueryGwangyaPostsService.kt
- 광야 게시물 리스트를 반환하는 로직 구현
- cursor 기반 페이지네이션 구현
광야 게시물들을 반환할때 쿼리메소드 방식으로 offset 기반 페이지네이션을 구현했을시에 생기는 게시물 중복 문제와 성능문제를 해결하기 위해서
queryDsl을 사용해서 cursor 기반 페이지 네이션을 구현하였습니다.
cursor 기반 페이지네이션을 처음 만들어봐서 이상한점 피드백 부탁드립니다.
디코에서 리뷰 받았던 필드명을 generationTime -> createdAt으로 수정하였습니다.
=> 광야 게시물 반환시 cursor 기반 페이지네이션 구현

src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/dto/GwangyaPostsRegistrationDto.kt
광야 게시물 등록시 content 필드를 NotNull에서 NotBlank로 변경하여서 공백도 허용하지 않도록 변경하였습니다.
=> 광야 게시물 등록시 content 공백도 허용하지 않도록 변경

src/main/kotlin/team/themoment/gsmNetworking/global/security/oauth/CustomOauth2UserService.kt, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
학생용 이메일이 아닐경우에 특정 주소로 리다이렉트 되도록 추가하였습니다.
oauthService에서 HttpServletResponse를 의존하고 있어서 추후에 리펙터링이 필요해 보입니다.
=> 학생용 이메일이 아닐때 리다이렉트 설정

src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/controller/GwangyaController.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/dto/GwangyaPostDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/dto/GwangyaPostRegistrationDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/repository/GwangyaCustomRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/repository/GwangyaCustomRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/service/GenerateGwangyaPostService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/gwangya/service/QueryGwangyaPostService.kt
광야 게시글을 지칭하는 명사를 posts에서 post로 수정
기존 광야 게시글을 지칭하는 명사인 posts는 게시물이라는 의미로 지칭하였었는데 복수 명사이므로 수정하였습니다.
=> 광야 게시글을 지칭하는 명사를 posts에서 post로 수정

src/main/kotlin/team/themoment/gsmNetworking/common/socket/sender/StompSender.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/domain/Header.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/domain/UserHeaderType.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/domain/UserMessageInfo.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/dto/domain/MessageMetaDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/MessageCustomRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/MessageCustomRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/repository/UserMessageInfoRepository.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/impl/CheckMessageServiceImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/impl/QueryMessageServiceImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/message/service/impl/SaveMessageServiceImpl.kt
채팅 기능 리팩토링을 진행하였습니다.
`MessageMetaDto`의 필드를 알맞게 수정   
`lastViewedChatId: UUID?` -> `lastViewedEpochMilli: Long
`
`UserMessageInfo`에 `Header` 연관관계 추가
`UserMessageInfoRepository`의 쿼리 기능을 `MessageCustomRepository`로 이동
=> 채팅 기능 리팩토링

.github/workflows/GSM-Networking-Develop-CD.yml, .github/workflows/GSM-Networking-Develop-Merge-CI.yml
- Develop 브랜치 CD 수정
기존 디벨롭 브랜치의 CI/CD 코드를 가져오는 브랜치 설정이 안되어있어서 main 브랜치 기준으로 배포가 되는거 같아서 수정하였습니다.
=> Develop 브랜치 CD 수정

src/main/kotlin/team/themoment/gsmNetworking/domain/board/domain/Board.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/comment/domain/Comment.kt
Board, Comment 엔티티의 작성자 컬럼의 연관관계 어노테이션을 `@OneToOne` -> `@ManyToOne` 으로 수정하였습니다.
=> Board, Comment 엔티티 연관관계 어노테이션 수정

src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/impl/BoardService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/comment/dto/AuthorDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/comment/service/impl/CommentService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/domain/Mentor.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/domain/TempMentor.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/MentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/MyMentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/SearchTempMentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/TempMentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/MentorCustomRepositoryImpl.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/service/impl/TempMentorService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/user/domain/User.kt, src/test/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryAllMentorsUseCaseTest.kt
기존에 멘토 정보를 조회할때 프론트 단에서 `temporaryImgNumber` 랜덤 값을 생성하여 사용했습니다.
프론트 단에서 `hydration` 관련 이슈가 발생하여 서버에서 `temporaryImgNumber` 랜덤 값을 멘토 or 멘티 생성시 랜덤 값을 생성하여 저장 후 반환하는 방식으로 변경하였습니다.
- `/api/v1/temp-mentor`
- `/api/v1/temp-mentor/search/{userName}`
- `/api/v1/temp-mentor/{id}`
- `/api/v1/user/user-id`
- `/api/v1/board/{boardId}`
- `/api/v1/comment/{commentId}`
- 위 API 반환 값으로 `temporaryImgNumber` 필드를 추가하였습니다.
- `User` 엔티티를 생성할 때 해당 엔티티의 필드인 `temporaryImgNumber` 를 `0~6` 까지의 랜덤 값을 저장하여 멘토와 멘티 필드에 추가하였습니다.
`temporaryImgNumber` 값은 엔티티 생성 시에만 저장되기 때문에 기존 멘토, 멘티 엔티티의 필드 초기화가 필요합니다.
해당 DML 쿼리를 실행하여 `0~6`의 랜덤 값으로 대치하는 작업이 필요합니다.
```sql
UPDATE user
SET temporary_img_number = FLOOR(RAND() * 7);
```
```sql
UPDATE temp_mentor
SET temporary_img_number = FLOOR(RAND() * 7);
```
=> 임시 프로필 이미지 번호 필드 추가

src/main/kotlin/team/themoment/gsmNetworking/domain/comment/domain/Comment.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/user/domain/User.kt
유저가 게시글을 작성한 상태에서 유저를 삭제할 때 연관관계 오류가 발생하는 현상을 해결하였습니다.
- User - Board 간의 연관관계에서 CasCade ALL 설정
- Comment - replyComment 간의 연관관계에서 CasCade ALL 설정
=> 게시글 cascade 설정

src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
선생님 권한인 사용자 인지 반환 API의 권한을 `USER`, `TEMP_USER`, `TEACHER` 권한으로 확장하였습니다.
=> 선생님 권한인 사용자 인지 반환 API 권한 확장

src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
멘티도 프로필 사진 등록 API를 사용할 수 있게 권한을 확장하였습니다.
- `/api/v1/file`, `/api/v1/user/profile-url` 해당 두 API에 대해 `TEMP_USER` 권한인 멘티도 요청을 보낼 수 있게 권한을 확장하였습니다.
=> 프로필 사진 업로드 멘티 권한 추가

src/main/kotlin/team/themoment/gsmNetworking/domain/mentee/dto/MenteeInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentee/service/impl/MenteeService.kt
나의 멘토 정보 반환 API에 프로필 사진 필드를 추가하였습니다.
- 멘티도 프로필 이미지 등록이 가능해지면서 나의 멘티 정보 반환 API에 `profileUrl` 필드를 추가하였습니다.
=> 나의 멘티 정보 반환 API 필드 추가

src/main/kotlin/team/themoment/gsmNetworking/domain/user/service/impl/UserService.kt
프로필 이미지 등록시 해당 유저의 게시글이 삭제되는 현상이 발생하였습니다.
프로필 이미지 등록시 새로운 유저 객채를 생성하여 save하는데, boards, comments, likes, defaultImgNumber 컬럼이 누락되어 있어서 추가하였습니다.
=> HotFix 프로필 이미지 등록시 발생하는 이상현상

src/main/kotlin/team/themoment/gsmNetworking/domain/user/domain/User.kt, src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
defualt 이미지 숫자 변경 API의 권한 설정과 로직을 수정하였습니다.
- defualt 이미지 숫자 변경 API의 시큐리티 url 매핑 설정을 추가하였습니다.
- 변경시 프로필 url이 있다면 null로 변경하는 로직을 추가하였습니다.
- 프로필 이미지가 등록되어 있는 상태에서 해당 API 호출시 default 이미지로 변경되기 위해 변경하였습니다.
=> 기본 이미지 변경 API 권한, 로직 설정

src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
누락된 게시글 관련 권한 매핑을 추가하였습니다.
- 게시글 관련 API 권한 매핑 추가 (TEMP_USER, USER, TEACH, ADMIN)
- 게시글 고정 API 권한 매핑 추가 (TEACHER)
=> 누락된 게시글 관련 시큐리티 권한 매핑 추가

src/main/resources/application-local.yml, src/main/resources/application-prod.yml
서버버 로그에 지속적으로 `Too many login attempts, please try again later. For more information` 해당 오류 메시지가 지속적으로 발생하였습니다.
스프링 엑추레이터가 헬스체크를 진행 시 `MailHealthIndicator` 에서 메일 서버 테스트 커넥트를 진행하는 것을 확인하였습니다.
해당 작업을 주기적으로 실행하는것은 어플리케이션에 영향을 줄 수 있다고 생각하여 mail에 관련된 헬스체크를 진행하지 않도록 설정을 추가하였습니다.
해당 작업 이후 주기적을 발생하는 헬스체크에서 메일관련 헬스체크를 disabled하여 어플리케이션의 다른 로직들까지 영향을 주는것을 막은 작업입니다.
추가로 메일을 전송하는 로직을 동작시 위의 오류가 발생하는 것을 확인하였습니다. 해당 부분에 대해 추후에 원인을 파악하여 고쳐보도록 하겠습니다.
=> 이메일 엑추레이터 헬스체크 비활성화

src/main/kotlin/team/themoment/gsmNetworking/global/security/SecurityConfig.kt
멘티가 멘토 리스트 API에 대해 403 에러가 발생하여 멘토 관련 권한 매핑의 레벨을 수정하였습니다.
- `/api/v1/mentor/**` (멘토, 선생님)
- `/api/v1/mentor` GET (멘티, 멘토, 선생님 ...)
- `/api/v1/mentor` POST (멘티, 인증 안된 유저)
위와 같은 구조를 아래와 같이 변경하였습니다.
- `/api/v1/mentor` GET (멘티, 멘토, 선생님 ...)
- `/api/v1/mentor` POST (멘티, 인증 안된 유저)
- `/api/v1/mentor/**` (멘토, 선생님)
=> 멘토 관련 API 권한 매핑 수정

src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/MentorCustomRepositoryImpl.kt
내 멘토 정보 조회시 반환되는 dto객체의 id값을 mentor id에서 user id로 변경하였습니다.
=> 나의 멘토 정보 조회시 id값 user id값으로 변경

src/main/kotlin/team/themoment/gsmNetworking/domain/board/dto/BoardAuthorDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/dto/BoardInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/board/service/impl/BoardService.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/MentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/dto/TempMentorInfoDto.kt, src/main/kotlin/team/themoment/gsmNetworking/domain/mentor/repository/MentorCustomRepositoryImpl.kt, src/test/kotlin/team/themoment/gsmNetworking/domain/mentor/service/QueryAllMentorsUseCaseTest.kt
OS 내장 메신저를 사용하는 기능 적용을 위해 게시글 상세조회 작성자와 멘토 리스트 API response에 phoneNumber 필드를 추가하였습니다.
=> 게시글 작성자, 멘토 리스트 dto phoneNumber 필드 추가
